# Generated by Django 3.0.8 on 2020-08-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezcoder', '0002_caps_shoes_watches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/assets')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('img2', models.ImageField(upload_to='static/assets')),
                ('title2', models.CharField(max_length=100)),
                ('price2', models.IntegerField()),
                ('img3', models.ImageField(upload_to='static/assets')),
                ('title3', models.CharField(max_length=100)),
                ('price3', models.IntegerField()),
                ('img4', models.ImageField(upload_to='static/assets')),
                ('title4', models.CharField(max_length=100)),
                ('price4', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Caps',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
        migrations.DeleteModel(
            name='Watches',
        ),
    ]
