# Generated by Django 3.0.8 on 2020-08-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tezcoder', '0003_auto_20200810_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='img',
            new_name='imgCap',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='img2',
            new_name='imgCloth',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='img3',
            new_name='imgShoe',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='img4',
            new_name='imgWatch',
        ),
    ]
